### ISSUE TITLE
Problem starting kernel: org.zeromq.ZMQException: Errno 48 : Address already in use

### ISSUE THREAD

**Issue by themoritz** [Kotlin/kotlin-jupyter#136]
Whenever I start the kernel I get this error message:

```
[I 11:50:44.335 NotebookApp] KernelRestarter: restarting kernel (2/5), keep random ports
[main] INFO ikotlin - Kernel args: -classpath=/home_dir/z003wy1/.anaconda/lib/python3.7/site-packages/run_kotlin_kernel/jars/lib-0.8.3.231.jar:/home_dir/z003wy1/.anaconda/lib/python3.7/site-packages/run_kotlin_kernel/jars/api-0.8.3.231.jar:/home_dir/z003wy1/.anaconda/lib/python3.7/site-packages/run_kotlin_kernel/jars/kotlin-script-runtime-1.4.30.jar:/home_dir/z003wy1/.anaconda/lib/python3.7/site-packages/run_kotlin_kernel/jars/kotlin-reflect-1.4.30.jar:/home_dir/z003wy1/.anaconda/lib/python3.7/site-packages/run_kotlin_kernel/jars/kotlin-stdlib-1.4.30.jar:/home_dir/z003wy1/.anaconda/lib/python3.7/site-packages/run_kotlin_kernel/jars/kotlin-stdlib-common-1.4.30.jar:/home_dir/z003wy1/.anaconda/lib/python3.7/site-packages/run_kotlin_kernel/jars/annotations-13.0.jar:/home_dir/z003wy1/.anaconda/lib/python3.7/site-packages/run_kotlin_kernel/jars/kotlinx-serialization-json-jvm-1.0.1.jar:/home_dir/z003wy1/.anaconda/lib/python3.7/site-packages/run_kotlin_kernel/jars/kotlinx-serialization-core-jvm-1.0.1.jar, /home_dir/z003wy1/.local/share/jupyter/runtime/kernel-735746ab-00da-4845-86d9-d01358570c49.json, -home=/home_dir/z003wy1/.anaconda/lib/python3.7/site-packages/run_kotlin_kernel
[main] INFO ikotlin - Starting server with config: KernelConfig(ports=[42928, 37999, 46476, 55395, 60405], transport=tcp, signatureScheme=hmac-sha256, signatureKey=7af7defd-ea72942ff945f3578c968819, pollingIntervalMillis=100, scriptClasspath=[/home_dir/z003wy1/.anaconda/lib/python3.7/site-packages/run_kotlin_kernel/jars/lib-0.8.3.231.jar, /home_dir/z003wy1/.anaconda/lib/python3.7/site-packages/run_kotlin_kernel/jars/api-0.8.3.231.jar, /home_dir/z003wy1/.anaconda/lib/python3.7/site-packages/run_kotlin_kernel/jars/kotlin-script-runtime-1.4.30.jar, /home_dir/z003wy1/.anaconda/lib/python3.7/site-packages/run_kotlin_kernel/jars/kotlin-reflect-1.4.30.jar, /home_dir/z003wy1/.anaconda/lib/python3.7/site-packages/run_kotlin_kernel/jars/kotlin-stdlib-1.4.30.jar, /home_dir/z003wy1/.anaconda/lib/python3.7/site-packages/run_kotlin_kernel/jars/kotlin-stdlib-common-1.4.30.jar, /home_dir/z003wy1/.anaconda/lib/python3.7/site-packages/run_kotlin_kernel/jars/annotations-13.0.jar, /home_dir/z003wy1/.anaconda/lib/python3.7/site-packages/run_kotlin_kernel/jars/kotlinx-serialization-json-jvm-1.0.1.jar, /home_dir/z003wy1/.anaconda/lib/python3.7/site-packages/run_kotlin_kernel/jars/kotlinx-serialization-core-jvm-1.0.1.jar], homeDir=/home_dir/z003wy1/.anaconda/lib/python3.7/site-packages/run_kotlin_kernel, resolverConfig=ResolverConfig(repositories=[kotlin.script.experimental.dependencies.RepositoryCoordinates@9f116cc, kotlin.script.experimental.dependencies.RepositoryCoordinates@12468a38, kotlin.script.experimental.dependencies.RepositoryCoordinates@1aa7ecca], libraries=org.jetbrains.kotlinx.jupyter.libraries.DefaultInfoLibraryResolver@59309333), resolutionInfoProvider=org.jetbrains.kotlinx.jupyter.libraries.StandardResolutionInfoProvider@5876a9af, embedded=false)
[main] ERROR ikotlin - exception running kernel with args: "-classpath=/home_dir/z003wy1/.anaconda/lib/python3.7/site-packages/run_kotlin_kernel/jars/lib-0.8.3.231.jar:/home_dir/z003wy1/.anaconda/lib/python3.7/site-packages/run_kotlin_kernel/jars/api-0.8.3.231.jar:/home_dir/z003wy1/.anaconda/lib/python3.7/site-packages/run_kotlin_kernel/jars/kotlin-script-runtime-1.4.30.jar:/home_dir/z003wy1/.anaconda/lib/python3.7/site-packages/run_kotlin_kernel/jars/kotlin-reflect-1.4.30.jar:/home_dir/z003wy1/.anaconda/lib/python3.7/site-packages/run_kotlin_kernel/jars/kotlin-stdlib-1.4.30.jar:/home_dir/z003wy1/.anaconda/lib/python3.7/site-packages/run_kotlin_kernel/jars/kotlin-stdlib-common-1.4.30.jar:/home_dir/z003wy1/.anaconda/lib/python3.7/site-packages/run_kotlin_kernel/jars/annotations-13.0.jar:/home_dir/z003wy1/.anaconda/lib/python3.7/site-packages/run_kotlin_kernel/jars/kotlinx-serialization-json-jvm-1.0.1.jar:/home_dir/z003wy1/.anaconda/lib/python3.7/site-packages/run_kotlin_kernel/jars/kotlinx-serialization-core-jvm-1.0.1.jar, /home_dir/z003wy1/.local/share/jupyter/runtime/kernel-735746ab-00da-4845-86d9-d01358570c49.json, -home=/home_dir/z003wy1/.anaconda/lib/python3.7/site-packages/run_kotlin_kernel"
org.zeromq.ZMQException: Errno 48 : Address already in use
	at org.zeromq.ZMQ$Socket.mayRaise(ZMQ.java:3546)
	at org.zeromq.ZMQ$Socket.bind(ZMQ.java:3000)
	at org.jetbrains.kotlinx.jupyter.JupyterConnection$Socket.<init>(connection.kt:27)
	at org.jetbrains.kotlinx.jupyter.JupyterConnection$Socket.<init>(connection.kt:23)
	at org.jetbrains.kotlinx.jupyter.JupyterConnection.<init>(connection.kt:137)
	at org.jetbrains.kotlinx.jupyter.IkotlinKt.kernelServer(ikotlin.kt:100)
	at org.jetbrains.kotlinx.jupyter.IkotlinKt.kernelServer$default(ikotlin.kt:97)
	at org.jetbrains.kotlinx.jupyter.IkotlinKt.main(ikotlin.kt:74)
```

Is there any way I can debug this further?

One thing that I noticed is that between kernel restart attempts the ports config (`ports=[42928, 37999, 46476, 55395, 60405]`) doesn't change. But I'm also not sure whether the exception indicates a busy port.

I installed the kernel with `conda install -c jetbrains-dev kotlin-jupyter-kernel` and am starting the `jupyter notebook --port=60350 --no-browser --ip=0.0.0.0`

**Comment by ileasile** [comment]
It seems that port 42928 (first in list, which is HEARTBEAT one) is in use.
Could you please check if it is true?

Also, does the situation change after restarting Jupyter server or the problem is permanent?

**Comment by themoritz** [comment]
Thanks for confirming that it's probably due to used port. I did a couple of tests and it turns out that a lot of the ports are just in use most of the time in the environment that I'm in And in some rare attempts I was able to get it to run so I'm gonna close the issue.

Maybe one suggestion would be to automatically pick new random ports if this exception occurs.

**Comment by ileasile** [comment]
Hopelessly, ports are picked by Jupyter server, not by kernel. That is why we can't pick other ones.

**Comment by themoritz** [comment]
Ah of course, got it.
