### ISSUE TITLE
Kernel spec produced for Windows is invalid

### ISSUE THREAD

**Issue by jjkavalam** [Kotlin/kotlin-jupyter#19]
### System requirements
- Windows (Mine is Windows 10, this problem must be there for any Windows version)

### Steps to reproduce

- Clone the repository and run `gradlew install`
- After that from suitable command prompt such as the 'Anaconda prompt' run `jupyter kernelspec list`

### Error 

```
(base) D:\jupyter-kernels\kotlin-jupyter>jupyter kernelspec list
[ListKernelSpecs] WARNING | Error loading kernelspec 'kotlin'
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\jupyter_client\kernelspec.py", line 258, in get_all_specs
    spec = self._get_kernel_spec_by_name(kname, resource_dir)
  File "D:\Anaconda3\lib\site-packages\jupyter_client\kernelspec.py", line 201, in _get_kernel_spec_by_name
    return self.kernel_spec_class.from_resource_dir(resource_dir)
  File "D:\Anaconda3\lib\site-packages\jupyter_client\kernelspec.py", line 47, in from_resource_dir
    kernel_dict = json.load(f)
  File "D:\Anaconda3\lib\json\__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "D:\Anaconda3\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "D:\Anaconda3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 2 column 32 (char 33)
Available kernels:
  kotlin        C:\Users\jjkav\.ipython\kernels\kotlin
  javascript    C:\Users\jjkav\AppData\Roaming\jupyter\kernels\javascript
  python3       D:\Anaconda3\share\jupyter\kernels\python3

```

As can be seen there is an issue with the `kernel.json` installed by kotlin-jupyter:
```
json.decoder.JSONDecodeError: Invalid \escape: line 2 column 32 (char 33)
```

**Comment by sciencedude100** [comment]
Even after trying to replace `\` with `\\` it still fails for me.
`[W 19:25:28.771 NotebookApp] Error loading kernelspec 'kotlin'
    Traceback (most recent call last):
      File "C:\Users\scien\Anaconda3\lib\site-packages\jupyter_client\kernelspec.py", line 258, in get_all_specs
        spec = self._get_kernel_spec_by_name(kname, resource_dir)
      File "C:\Users\scien\Anaconda3\lib\site-packages\jupyter_client\kernelspec.py", line 201, in _get_kernel_spec_by_name
        return self.kernel_spec_class.from_resource_dir(resource_dir)
      File "C:\Users\scien\Anaconda3\lib\site-packages\jupyter_client\kernelspec.py", line 47, in from_resource_dir
        kernel_dict = json.load(f)
      File "C:\Users\scien\Anaconda3\lib\json\__init__.py", line 296, in load
        parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
      File "C:\Users\scien\Anaconda3\lib\json\__init__.py", line 348, in loads
        return _default_decoder.decode(s)
      File "C:\Users\scien\Anaconda3\lib\json\decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\Users\scien\Anaconda3\lib\json\decoder.py", line 353, in raw_decode
        obj, end = self.scan_once(s, idx)
    json.decoder.JSONDecodeError: Invalid \escape: line 2 column 32 (char 33)`

**Comment by altavir** [comment]
Seems to be working now on Win10. Close?

**Comment by ileasile** [comment]
Issue was fixed with this commit: https://github.com/Kotlin/kotlin-jupyter/commit/f12711836e3ae952e082694cc7c032729b9b4dec

Note that it's not obvious where Jupyter finds kernel specs. For more information look into this: https://jupyter-client.readthedocs.io/en/stable/kernels.html#kernel-specs

If you're still having troubles, old kernel spec in some other path may be the reason. In my case, it was old spec in `~\AppData\Roaming\jupyter\kernels\kotlin`. To fix it, you may specify the path to this spec in `gradle.properties`.

If it doesn't help, feel free to open a new issue.
