### ISSUE TITLE
Setting `JupyterApiResourcesTask.libraryProducers` doesn't disable `kapt` that causes incompatibility with JDK 16

### ISSUE THREAD

**Issue by CommanderTvis** [Kotlin/kotlin-jupyter#322]
Build script: https://github.com/mipt-npm/kmath/blob/foreign-memory/kmath-jupyter/build.gradle.kts
Exception:
```
Caused by: java.lang.IllegalAccessError: class org.jetbrains.kotlin.kapt3.base.KaptContext (in unnamed module @0x6003f591) cannot access class com.sun.tools.javac.util.Context (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.util to unnamed module @0x6003f591
	at org.jetbrains.kotlin.kapt3.base.KaptContext.<init>(KaptContext.kt:29)
	at org.jetbrains.kotlin.kapt3.base.Kapt.kapt(Kapt.kt:33)
```

**Comment by ileasile** [comment]
Hi! Please set `kotlin.jupyter.add.scanner` Gradle property to `false` (i.e. in `gradle.properties`) and recheck

**Comment by CommanderTvis** [comment]
> kotlin.jupyter.add.scanner

That works, but this should be mentioned in the [documentation](https://github.com/Kotlin/kotlin-jupyter/blob/master/docs/libraries.md#avoiding-using-annotation-processor).

**Comment by ileasile** [comment]
It is mentioned a bit above in the same document

**Comment by ileasile** [comment]
You may PR edits to this file to make it clearer

**Comment by CommanderTvis** [comment]
> It is mentioned a bit above in the same document

It is, but it's unclear that removing that dependency disables `kapt`.

**Comment by ileasile** [comment]
Will be glad to merge the changes to the documentation that makes it clearer
